### ISSUE TITLE
Adding support for OpenAPI documents

### ISSUE THREAD

**Issue by gayanper** [valentjn/languagetool-languageserver#121]
I'm looking into how I can reuse this tool to validate OpenAPI document's descriptions, summaries, and titles etc. I would like to know if there is a extension point which I can provide the regions of the document that I would like to inspect for grammer and spellings. So for OpenAPI document I can provide those regions based on the OpenAPI grammer.

**Comment by valentjn** [comment]
I see at least two possibilities:

* You can either extract the text snippets outside of LT<sub>E</sub>X and feed them individually to LT<sub>E</sub>X to check them. How to do that exactly (via language server, via CLI, via calling from Kotlin/Java, etc.) highly depends on your use case. Alternatively, if you don't have markup in the snippets, you can also use LanguageTool directly.
* Or you can add the functionality of extracting text snippets to LT<sub>E</sub>X itself and feed LT<sub>E</sub>X the whole document. However, I'm not sure about this since OpenAPI documents are JSON/YAML documents, which shouldn't be checked by default, so we would need to tell them apart somehow.
