### ISSUE TITLE
Add gitcommit files support

### ISSUE THREAD

**Issue by vigoux** [valentjn/languagetool-languageserver#132]
Hi and thanks for this awesome tool and your work ! This is a really handy tool !

**Is your feature request related to a problem? Please describe.**

When I edit my commit message, I like to have the things I write grammar-checked, and I'd like to use ltex-ls for that.

**Describe the solution you'd like**

There is actually two solutions:
1. Add a gitcommit filetype, that ignores comments in the file (starting with `#`)
2. Add the ability to create custom filetypes, with something like regexes to "parse" them.

**Describe alternatives you've considered**

I tried using the `plaintext` version, but it is not that great.

**Additional context**

Not sure if that applies here.

**Comment by valentjn** [comment]
Thanks for the suggestion. Regarding the suggested solutions:
1. Which language ID(s) should this be mapped to (depends on your editor/language client)? VS Code apparently uses `git-commit`.
2. I doubt that a regex would be really useful for the general case. Most languages cannot be expressed with a mere regex.

**Comment by vigoux** [comment]
In neovim (which I use), we use gitcommit but I guess this is fine.

Indeed you can't represent languages using simple regexes, but with a combination of those, one can have basic things working (say spellcheck comments and so on).

**Comment by valentjn** [comment]
This is implemented now.

While LT<sub>E</sub>X LS will support both `git-commit` and `gitcommit` (in the sense that it will parse documents as Git commits when provided with one of these two LSP language IDs), the default value of [`ltex.enabled`](https://valentjn.github.io/ltex/settings.html#ltexenabled) will only contain `git-commit`. The reason is that [the LSP spec recommends `git-commit`](https://microsoft.github.io/language-server-protocol/specification#textDocumentItem), and IMO all servers and clients should follow the recommendations of the spec (Neovim struggles a bit there, at least with the LSP language IDs). This means that on Neovim, this feature will only work if the default of [`ltex.enabled`](https://valentjn.github.io/ltex/settings.html#ltexenabled) is changed or if the filetype is mapped to `git-commit`.

**Comment by mjlbach** [comment]
> Neovim struggles a bit there, at least with the LSP language IDs

I don't think we have any issues with this? We just add the custom mapping per server in the lspconfig plugin. I can add it for git-commit no problem.

**Comment by valentjn** [comment]
@mjlbach That's what I meant with ”if the filetype is mapped to `git-commit`.“ Not sure if possible, but Neovim should use the LSP language IDs listed in the LSP spec by default for all servers, without having to add the relevant ones to a mapping for each server.
