### ISSUE TITLE
Listing on the LS lists?

### ISSUE THREAD

**Issue by goyalyashpal** [valentjn/languagetool-languageserver#219]
Hi!

How will the ltex-ls be listed on these sites?
- https://langserver.org
- https://microsoft.github.io/language-server-protocol/implementors/servers/

These sites have columns for only a single language, and LTEX-LS supports multiple languages (tex, markdown) - so, how will it be listed on these sites?? 😅

**Comment by valentjn** [comment]
It's already listed on <https://microsoft.github.io/language-server-protocol/implementors/servers/> under the language LanguageTool, since that's what it's about. The notion of languages is very ambiguous for LT<sub>E</sub>X as there are two kinds of languages T<sub>E</sub>X deals with: code languages like L<sup>A</sup>T<sub>E</sub>X, Markdown, etc., and natural languages like English, German, etc. (The listed implementation language Java isn't up-to-date anymore, though.)

I can open a PR for langserver.org.

**Comment by goyalyashpal** [comment]
> The listed implementation language Java isn't up-to-date anymore, though.

so, Kotlin then?

https://github.com/microsoft/language-server-protocol/pull/1665

**Comment by yashpalgoyal1304** [comment]
and would u have any objection on addition in langserver.org ??

**Comment by goyalyashpal** [comment]
> I can open a PR for langserver.org.

yep, that'd be awesome :smiley:

**Comment by yashpalgoyal1304** [comment]
https://github.com/microsoft/language-server-protocol/pull/1665

**Comment by valentjn** [comment]
langserver/langserver.github.io#305
