### ISSUE TITLE
Release latest develop

### ISSUE THREAD

**Issue by Jakob-Koschel** [valentjn/languagetool-languageserver#236]
Hey!

Looks like support for git commit messages was merged in #132 but it's not included in 15.2.0. If it would at all be possible to generate a new release, with what is currently in `develop` that would save me a lot of time trying to figure out how to create a release myself.

Thanks for this great project, I'm using it for latex and markdown and really enjoy using it!

EDIT: just realized there is: https://github.com/valentjn/ltex-ls/releases/tag/nightly which I'll be taking a look at now.
EDIT2: looks like that nightly build is broken (`Uncaught exception: Header must provide a Content-Length property.` in coc.nvim)

**Comment by valentjn** [comment]
Just released 16.0.0. Note that the nightly release is not different from any normal release, except for the version number and the release date in `changelog.xml`. In case you're having problems with nightly releases, you are probably also going to have them with the regular release, and therefore, you should report them (here or in third-party repositories). Make sure the problem is actually caused by LT<sub>E</sub>X LS before reporting it here.
