### ISSUE TITLE
[Question] Why Maven instead of Gradle?

### ISSUE THREAD

**Issue by jcs090218** [valentjn/languagetool-languageserver#66]
Hi @valentjn,

I have a question why the commit ff43f038c999b1f8860a1e14ccd6755bbe8c476b. I am just curious and want to know the reason on this move.

Thanks! :)

**Comment by valentjn** [comment]
Gradle seemed to cause more problems for me than it solved. You don't see it in the commit history (because only the final results made it in there), but every time something related to the build system needed to be changed, an overly large amount of googling was necessary to solve any arising problems (and it wasn't just because of me – I knew CMake and SCons). IIRC, old problems that I deemed solved resurfaced when solving new ones. A lot of "magic" seemed to be involved.

Plus (and of course this is related), I never understood the language really (I don't even know Groovy), and I didn't want to learn yet another language just for a build system, because that's time I'd rather spend on the actual software. A scripting language in the build system is of course a huge point of flexibility, but LT<sub>E</sub>X didn't need that at that point in time. Having clear XML files (which are not programs) containing the dependencies and the info which action is executed in which stage seemed more appealing to me.

I did a bit of googling back then, and it turned out a lot of projects were migrating from Maven to Gradle, fewer the other way around. However, in itself, that's not a great argument for me; so I looked at the reasons *why* people are migrating, and [this blog post](https://phauer.com/2018/moving-back-from-gradle-to-maven/) finally convinced me to try Maven while I was restructuring the whole project anyway.

Looking back now, Maven isn't an ideal solution either, its most important drawback probably being the lack of incremental recompilation, but at least I understand my own build system now more or less, and that's an absolute necessity for me as maintainer.
