### ISSUE TITLE
Support for editors other than VSCode

### ISSUE THREAD

**Issue by Ailrun** [valentjn/languagetool-languageserver#96]
**Is your feature request related to a problem? Please describe.**
Currently, code actions like `Add "..." to dictionary` or `Disable rule` work only in VSCode, as their behavior depends on VSCode setting modification. It will be nicer if it can delegate the responsibility of modifying the setting to clients so that those actions work with other editors, e.g., Emacs.

**Describe the solution you'd like**
Delegating the responsibility of modifying the setting to clients if possible. (Though this requires some client update too)

**Describe alternatives you've considered**

**Additional context**
I'm using [LSP-mode](https://github.com/emacs-lsp/lsp-mode) on Emacs with [lsp-ltex](https://github.com/emacs-languagetool/lsp-ltex).

**Comment by valentjn** [comment]
The language client *is* already responsible to perform the necessary configuration changes, [like the README says](https://github.com/valentjn/ltex-ls/blob/e77537102c3626986bf6784a5eb4ca35d4bca53b/README.md#commands):

> Some commands are handled by LT<sub>E</sub>X LS, while others must be handled by the language client. This is in contrast to the LSP specification, which recommends that the server handles all commands. However, handling of some commands by the client is necessary as these commands change the client configuration, which the LSP does not allow server-side.

For example, the [documentation for `_ltex.addToDictionary`](https://github.com/valentjn/ltex-ls/blob/e77537102c3626986bf6784a5eb4ca35d4bca53b/README.md#_ltexaddtodictionary-client) (the command behind `Add '...' to dictionary`) says:

> `_ltex.addToDictionary` is executed by the client when it should add words to the dictionary by adding them to [`ltex.dictionary`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexdictionary).

It works like this: First, the language client requests code actions from the server. If there's an unknown word, then a code action with kind `quickfix.ltex.addToDictionary` will be returned by LT<sub>E</sub>X LS. That code action contains the command `_ltex.addToDictionary` and its necessary parameters ([as documented](https://github.com/valentjn/ltex-ls/blob/e77537102c3626986bf6784a5eb4ca35d4bca53b/README.md#_ltexaddtodictionary-client)). If the user runs the code action, the language client has to implement the command `_ltex.addToDictionary` and do what LT<sub>E</sub>X LS expects it to do according to the docs.

In the case of VS Code, [the language client `vscode-ltex` implements these commands](https://github.com/valentjn/vscode-ltex/blob/17bea642a1588b4b50cbee1ca6d2098864d9dde3/src/CommandHandler.ts#L93-L98), not the editor (VS Code) itself. If the language client you use doesn't implement the commands, then this is a problem of the language client and not of LT<sub>E</sub>X LS.

There's also the custom request [`ltex/workspaceSpecificConfiguration`](https://github.com/valentjn/ltex-ls/blob/e77537102c3626986bf6784a5eb4ca35d4bca53b/README.md#ltexworkspacespecificconfiguration-), which takes precedence over the configuration returned by `workspace/configuration`. It allows to implement file-based dictionaries, so that the &ldquo;normal&rdquo; configuration (whatever format the editor is using; in the case of VS Code, it's `settings.json`) doesn't get too cluttered.

**Comment by Ailrun** [comment]
Oh I was confused since the documentation mentions `ltex.dictionary`, which has a link to VSCode specific setting. OK, I will check lsp-ltex side to make this work. Thank you for the answer.

Maybe it's worthwhile to update README to make it less confusing? What do you think?

**Comment by valentjn** [comment]
> the documentation mentions ltex.dictionary, which has a link to VSCode specific setting

Again, I'm not sure what you mean. The [documentation of `_ltex.addToDictionary`](https://github.com/valentjn/ltex-ls/blob/e77537102c3626986bf6784a5eb4ca35d4bca53b/README.md#_ltexaddtodictionary-client) links to `ltex.dictionary`, but the docs of [`ltex.dictionary`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexdictionary) don't say anywhere that's a VS-Code-specific setting, because it isn't. Only the parts about multi-scope settings and external files are tagged as client-specific, as clearly marked with the striped line. That's because multi-scope settings and external files are implemented by the language client. Those are “bonus features” of vscode-ltex, if you will.

However, this has to be separated from the fact that `_ltex.addToDictionary` has to be implemented by the client. If it doesn't, then that command obviously won't work at all. IMO, the README is pretty clear about that.

I'm not sure how to make the available info any clearer. What would your proposal look like?

**Comment by Ailrun** [comment]
Oh sorry. It was indeed my misunderstanding. Thank you for your patience on my non-sense. I will close this issue.
